### ISSUE TITLE
I dont understand what is this error means

### ISSUE THREAD

**Issue by hchuanZ** [JunMa11/FLARE2021#1]
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.

**Comment by JunMa11** [comment]
Hi @hchuanZ ,

Could your please provide your Dockerfile details?
and how do you get this error?

**Comment by hchuanZ** [comment]
my dockerfile is&nbsp;
FROM pytorch/pytorch:1.5.1-cuda10.1-cudnn7-runtime
RUN apt-get update &amp;&amp; apt-get install -y --no-install-recommends \
   # we have found python3.7 in base docker
   python3-pip \
   python3-setuptools \
   build-essential \
   &amp;&amp; \
   apt-get clean &amp;&amp; \
   python -m pip install --upgrade pip
WORKDIR /workspace
COPY ./   /workspace

RUN pip install pip -U
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN pip install natsort -i https://pypi.douban.com/simple
RUN pip install nibabel -i https://pypi.douban.com/simple
RUN pip install numpy -i https://pypi.douban.com/simple

CMD ["bash", "predict.sh"]
the predict.sh is&nbsp;
export CUDA_VISIBLE_DEVICES=1
export nnUNet_raw_data_base="$PWD"
export RESULTS_FOLDER="$PWD/datasets/"
predict -i "/workspace/inputs/"  -o "/workspace/outputs/"
setup.py is&nbsp;
from setuptools import setup, find_namespace_packages

setup(name='Jiujiuhaiziba',
      version='0.1',
      entry_points={
          'console_scripts': [
              'predict = inference.predict:main'
          ],
      }
      )


I build this image and save it as tar.gz


then I try to run it on my pc.
D:\workspace\test_docker_fold&gt;docker container run --gpus=all --name jiujiuhaiziba --rm -v $PWD/inputs/:/workspace/inputs/ -v $PWD/teamname_outputs/:/workspace/outputs/ jiujiuhaiziba:latest /bin/bash -c "sh predict.sh"
docker: Error response from daemon: create $PWD/inputs: "$PWD/inputs" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.



D:\workspace\test_docker_fold&gt;docker container run --gpus=all --name jiujiuhaiziba --rm -v %PWD%/inputs/:/workspace/inputs/ -v %PWD%/teamname_outputs/:/workspace/outputs/ jiujiuhaiziba:latest /bin/bash -c "sh predict.sh"
docker: Error response from daemon: create %PWD%/inputs: "%PWD%/inputs" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.



D:\workspace\test_docker_fold&gt;docker container run --gpus=all --name jiujiuhaiziba --rm -v /d/workspace/test_docker_fold/inputs:/workspace/inputs/ -v /d/workspace/test_docker_fold/outputs/:/workspace/outputs/ jiujiuhaiziba:latest /bin/bash -c "sh predict.sh"
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JunMa11/FLARE2021"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月29日(星期四) 晚上7:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JunMa11/FLARE2021] I dont understand what is this error means (#1)





 
Hi @hchuanZ ,
 
Could your please provide your Dockerfile details?
 and how do you get this error?

**Comment by JunMa11** [comment]
Hi @hchuanZ 

It may be the docker is too old. Could you please run `docker version` and share the details.

2. please try
```
docker container run --gpus=all --name jiujiuhaiziba --rm -v ./inputs:/workspace/inputs/ -v ./outputs/:/workspace/outputs/ jiujiuhaiziba:latest /bin/bash -c "sh predict.sh"
```

**Comment by JunMa11** [comment]
please also try
```
docker container run --gpus=all --name jiujiuhaiziba --rm -v .\inputs:/workspace/inputs/ -v .\outputs/:/workspace/outputs/ jiujiuhaiziba:latest /bin/bash -c "sh predict.sh"
```

```
docker container run --name jiujiuhaiziba --rm -v .\inputs:/workspace/inputs/ -v .\outputs/:/workspace/outputs/ jiujiuhaiziba:latest /bin/bash -c "sh predict.sh"
```

**Comment by JunMa11** [comment]
Hi @hchuanZ 
If your docker is the 20.* version and all the above commands do not work.
Please send your tar file to flare21@aliyun.com. We will help you to evaluate it under linux system.

Note: the simpleitk version sholud be <=2.02

**Comment by hchuanZ** [comment]
https://drive.google.com/file/d/1OMcmJ6kfKu66FJsetCjH_tBTAmYcf7lP/view?usp=sharing
