### ISSUE TITLE
GPU Memory 

### ISSUE THREAD

**Issue by jizhang02** [JunMa11/FLARE2021#4]
Hello,
Based on my own idea, that computing a model's memory including several steps:
1. Loading the test data;
2. Loading the trained model;
3. Start predicting.

So my question is the maximum GPU memory you proposed is starting from when?
Because as I know the GPU memory is cumulative; for example, it already has a memory from the moment it starts reading data. If we talk about memory when simply calculating model predictions, it actually accumulates memory from the moment the program starts running (that is, from the moment it loads data, various libraries, etc.).
So I would like to know how you define the concept of maximum memory usage?
![image](https://user-images.githubusercontent.com/46089068/137757874-e3e81dec-fd5e-458f-b5b2-4bd63e720178.png)
From this figure, we can also see the memory is increasing from the beginning. We see the program runs for about 250 seconds. It starts from which stage? 
Thank you!

**Comment by JunMa11** [comment]
Hi @jizhang02,

Thanks for your question.

I agree with your explanation of the GPU memory.
In the evaluation code, we used  the memory consumption during model inference/predicting (step 3).

In the next FLARE iteration, we will consider using the Region of GPU-Time Curve to measure the GPU consumption, which can capture the whole GPU consumption during inference.

Best regards,
Jun

**Comment by jizhang02** [comment]
Hi, @JunMa11, thank you for your reply.
I agree with your use of the Region of GPU-Time Curve to monitor the memory usage of the model during prediction, which is also one of the intentions of FLARE, i.e. to design a model to achieve high-performance prediction with less memory.
I would like to ask why you only consider memory at the GPU level?
Because for now, CPU and GPU are coexisting and some devices only have CPU, so we are not sure if the model is running only on GPU or also in CPU as well.
As an example, the graph shows the memory usage of different programs in the operating system, which lists the CPU and GPU usage ratios as well as the memory usage.
![image](https://user-images.githubusercontent.com/46089068/137940702-36fce616-515c-4d7b-8eb6-66579f2905bd.png)
That is, a process or a running program may be on both the CPU and the GPU.
![image](https://user-images.githubusercontent.com/46089068/137944585-83cc817f-a4d0-4507-b694-e1785f3e19e2.png)
So, in a way, it's complicated.
So I think it's better to provide theoretical support when you publish some kind of evaluation criteria for memory, for example like metric Dice, which is convincible and universally applicable in the segmentation area. Because I am not an expert in memory and I don't know much about the code you shared.  Which creates some kind of ambiguity.
Thank you for reading this message.
Best wishes!

**Comment by JunMa11** [comment]
Hi @jizhang02 ,

Thanks for your comments very much.

> I would like to ask why you only consider memory at the GPU level?

This is because that RAM is usually not a big bottleneck when deploying segmentation models in (our) practice. So, we only consider the GPU memory.

Another thing I need to acknowledge is that there is a big limitation in FLARE. When designing the challenge, we thought all the solutions would be based on GPU and didn't realize that one can only use CPU. In the next iteration, we will also consider including CPU usage in the metrics.

Here are some lessons we learned from FLARE. Any further suggestions would be highly appreciated.

![image](https://user-images.githubusercontent.com/19947331/137992816-d7e7bc21-c493-4296-9228-668a3de82abb.png)


Best regards,
Jun
